---
name: Distributed Press
description: A beginner friendly, open-source publishing tool for the distributed
  web.
author:
  name: Distributed Press
  email: hello@distributed.press
  info:
url: https://distributed-press.sutty.nl
baseurl: ''
locales:
- en
show-subtitle: true
display-social-icons: false
social-icons-open-newtab: true
footer-text: This website is built with <a href="https://jekyllrb.com">Jekyll</a>
  and uses the <a href="http://stijnvc.github.io/holo-alfa/">Holo Alfa</a> Jekyll
  theme crafted by <a href="http://stijnvc.github.io/holo-alfa/">Stijn</a>. Made by
  <a href="https://sutty.nl/en/">Sutty</a>.
logo-image: img/logos/logo-distributedpress-grey.svg
theme-color-attr: "#ff0040"
ms-tile-color: "#ff0040"
theme-color: 255, 0, 64
text-color: 65, 64, 66
background-color: 255, 255, 255
display-author-post-page: true
display-author-front-page: true
date_format: "%b %-d, %Y"
nav-breaking-point: 520px
paginate: 3
display-next-prev-post: false
disqus-shortname:
twitter:
youtube:
instagram:
tumblr:
facebook:
google-plus:
reddit:
soundcloud:
medium:
linkedin:
github:
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:
var_on_the_web: On the web
var_read: Read
var_newer: Newer
var_older: Older
var_next_post: Next post
var_previous_post: Previous post
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read
var_post_by: Post by
var_guest_post_by: Guest post by
var_your_email: Your email
var_your_message: Your message
exclude:
- vendor
highlighter: rouge
kramdown:
  input: GFM
paginate_path: page-:num/
permalink: pretty
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    excerpt_separator: "<!--more-->"
title: Distributed Press
hostname: distributed-press.sutty.nl
linked_fields:
- menu
- post
plugins:
- jekyll-locales
- jekyll-distributed-press
- jekyll-linked-posts
- jekyll-order
- jekyll-relative-urls
onion-location: f5aoksf6ejagxboqhmps2u27i33sopshape26o45dgfxaeg7e3levqyd.onion
